---
name: "Initial test run"
systems:
  customerAcquisition:
    organic:
      name: "gaussian"
      parameters:
        mu: 5
        sigma: 5
    advertising:
      name: "gaussian"
      parameters:
        mu: 5
        sigma: 5
    events:
      name: "gaussian"
      parameters:
        mu: 5
        sigma: 5
    conversion:
      name: "gaussian"
      parameters:
        mu: 5
        sigma: 5
    churn:
      name: "gaussian"
      parameters:
        mu: 5
        sigma: 5
...
---
