---
name: "Initial test run"
consts:
  sub_price: 40
  pur_price: 500
  germination_rate: 0.5
  fuel_cpm: 0.22
  man_cost: [[63.53, 47.88, 41.90], 31.76]
  mat_cost: [[203.68, 169.01, 146.58], 105.86]
  reman_cost: [[87.10, 48.36, 42.70], 24.70]
  plants_per_unit: 30
  capex: [[1673.53, 210.93, 151.93], 928.66]
  germination_costs:
    cost_per_seed: 0.11471
    seeds_per_shelf: 400
    new_shelf_capex: 108.6
    shelf_running_cost: 1.03488
    new_shelving_unit_capex: 55
    shelves_per_shelving_unit: 6
    extra_production: 5
  plant_maturity:
    weeks2mature: 3
    mature_life: 2
  initial_shelf_counts: [3, 18]
systems:
  customerAcquisition:
    leadGen:
      name: "skew-norm"
      parameters:
        a: -4
        loc: 20
        scale: 5
    conversion:
      name: "gaussian"
      parameters:
        loc: 0.07
        scale: 0.1
    churn:
      name: "binomial"
      parameters:
        p: 0.0833
    cac_low:
      name: "gaussian"
      parameters:
        loc: 212.53
        scale: 20
    cac_med:
      name: "gaussian"
      parameters:
        loc: 118.40
        scale: 15
    cac_high:
      name: "gaussian"
      parameters:
        loc: 89.97
        scale: 10
  activeClients:
    unit:
      name: "skew-norm"
      parameters:
        a: -4
        loc: 6
        scale: 2
    subLength:
      name: "timer"
      parameters:
        steps: 12
    officePosition:
      name: "gaussian"
      parameters:
        loc: 5
        scale: 2.5