---
name: "deterministic_cs2_icp12"
period: "week"
steps: 260
runs: 1
sim_details:
  germinationStation:
    germination_costs:
      cost_per_seed: 0.11471
      seeds_per_shelf: 400
      new_shelf_capex: 108.6
      shelf_running_cost: 1.03488
      new_shelving_unit_capex: 55
      shelves_per_shelving_unit: 6
      extra_production: 3.5
    plant_maturity:
      weeks2mature: 3
      mature_life: 2
    initial_shelf_counts: [10, 60]
    active_varieties: 1
  cac:
    cac_low:
      name: "constant"
      parameters:
        value: 1487.72
    cac_med:
      name: "constant"
      parameters:
        value: 828.8
    cac_high:
      name: "constant"
      parameters:
        value: 629.8
  activeClients:
    distributions:
      unit:
        name: "constant"
        parameters:
          value: 20
      subLength:
        name: "constant"
        parameters:
          value: 4
      officePosition:
        name: "constant"
        parameters:
          value: 15
      churn:
        name: "timer"
        parameters:
          steps: 39
      plantDist:
        name: "constant"
        parameters:
          value: 0
    plant_request_length: 12
    client_details:
      subscription_price: 40
      purchase_price: 500
      plants_per_unit: 30
      initial_contract_period: 52
    cac:
      thresholds: [5, 10, 25]
  customerAcquisition:
    lead_growth: 1.005097
    lead_generation:
      name: "constant"
      parameters:
        value: 3
    conversion:
      name: "constantPercentage"
      parameters:
        p: 0.07
  build:
    man_cost: [[63.53, 47.88, 41.90], 31.76]
    mat_cost: [[203.68, 169.01, 146.58], 105.86]
    build_thresholds: [10, 20, 50]
    phase: 1
    phase_change: 20000
  install:
    install_cost: 12.5
  maintenance:
    maintenance_cost: 7.038
  transport:
    hq_position:
      name: "constant"
      parameters:
        value: 0
    fuel_cost: 0.22
    max_clients_serviced: 2
    labour_per_mile: 0.5
  op_cost:
    op_cost_dist:
      name: constant
      parameters:
        value: 1750
    upfront_costs: 12000






